AixLib/Building/HighOrder/House/MFD/BuildingAndEnergySystem/OneAppartment_Radiators.mo
AixLib/Building/HighOrder/House/MFD/EnergySystem/OneAppartment/Radiators.mo
AixLib/HVAC/HeatGeneration/Utilities/FuelCounter.mo
AixLib/HVAC/HumidifierAndDehumidifier/CoolerDehumidifier.mo
AixLib/HVAC/HumidifierAndDehumidifier/SteamHumidifier.mo
AixLib/HVAC/Interfaces/TwoPortMoistAirFluidprops.mo
AixLib/HVAC/Interfaces/TwoPortMoistAirTransportFluidprops.mo
AixLib/HVAC/OFD/Hydraulics/GroundFloor.mo
AixLib/HVAC/Storage/Storage.mo
AixLib/HVAC/Volume/Examples/MoistAirWithHeatTransfer.mo
AixLib/UsersGuide/Conventions/ModelTemplateDocumentation.mo
AixLib/UsersGuide/Conventions/RecordTemplateDocumentation.mo
AixLib/package.mo

issue56 HVAC clash

---

AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case600.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case600FF.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case620.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case640.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case650.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case650FF.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case900.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case900FF.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case920.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case940.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case950.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case950FF.mo

Modified altitude

---

AixLib/Fluid/HeatExchangers/Radiators/Radiator.mo

Correct typos in radiator

---

AixLib/Building/Components/Weather/BaseClasses/package.order
AixLib/Fluid/Movers/BaseClasses/package.order
AixLib/Fluid/Movers/package.order
AixLib/HVAC/HeatGeneration/package.order
AixLib/Media/package.order
AixLib/UsersGuide/package.order

fixing the package.order

---

AixLib/Building/Components/WindowsDoors/Window_ASHRAE140.mo
AixLib/Utilities/Examples/HeatTransfer_test.mo
AixLib/Utilities/HeatTransfer/HeatConv_inside.mo

Added equations for calculation of alpha according to EN ISO 6946 and constant alpha. Adapted in Examples/HeatTransfer_test.mo

Improved model for heat convection of inside walls

---

AixLib/Building/LowOrder/Examples/LowOrderExample.mo
AixLib/HVAC/HeatGeneration/IdealHeaterCooler.mo
AixLib/Utilities/Control/PITemp.mo

should solve pedantic issue #124

Issue124 lom example

---

AixLib/Resources/Include/AixLibSocketCommunication.h
AixLib/Utilities/Communication/SocketCommunication/Components/Internal/TCPCommunicatorBasic.mo
AixLib/Utilities/Communication/SocketCommunication/Components/TCPCommunicatorExample.mo
AixLib/Utilities/Communication/SocketCommunication/Components/package.mo
AixLib/Utilities/Communication/SocketCommunication/Examples/ExampleClientLoop.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/SocketConnect.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/SocketDisconnect.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/SocketInit.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/add2.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/package.order
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/SocketDestruct.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/SocketReceive.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/SocketSend.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/TCPConstructor.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertBytetoHex.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertBytetoSgl.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertDbltoHex.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertHextoByte.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertStrtoDbl.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/convertStrtoInt.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/package.mo
AixLib/Utilities/Communication/SocketCommunication/UsersGuide/Documentation/package.mo
AixLib/Utilities/Communication/SocketCommunication/UsersGuide/package.mo
AixLib/Utilities/Communication/SocketCommunication/package.mo

Hello everyone!
Everything in the branch should be now working. I think additional work is needed on providing proper examples also for the multi-socket case and the documentation should be revised.
I am still new to github so I hope a pull request for the branch is ok! Correct me if I am wrong.
Cheers,
Georg

Issue149 communication package

---

AixLib/HVAC/AirHandlingUnit/NoAHU.mo

changes constant block to CombiTimeTable

---

AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case600.mo
AixLib/Building/HighOrder/Examples/Validation/ASHRAE140/Case900.mo
AixLib/Building/LowOrder/Examples/ThermalZoneExample.mo
AixLib/Building/LowOrder/Examples/Validation/ASHRAE140/Case950.mo

this solves #204 
please note:
Couldn't find any usage of ```EEnergyMeter``` or ```TEnergyMeter``` in ```AixLib.Fluid.HeatExchangers.Utilities.FuelCounter```

Issue204 energy meter

---

AixLib/Building/HighOrder/House/MFD/Building/package.mo
AixLib/Building/HighOrder/House/MFD/package.order

this should close #195.
A package check for the Building-package lead to no related errors.

Deleted AixLib.Building.HighOrder.House.MFD.Building-Package

---

AixLib/Building/Components/Weather/RadiationOnTiltedSurface/RadOnTiltedSurf_Liu.mo
AixLib/DataBase/Weather/WeatherBaseDataDefinition.mo

Removed Non ASCII characters in files. 
@marcusfuchs is this renaming right?

Issue172 non ascii

---

AixLib/Building/LowOrder/BaseClasses/SolarRadWeightedSum.mo

This should fix bug if no windows are present

---

AixLib/Airflow/AirHandlingUnit/AHU.mo
AixLib/Airflow/AirHandlingUnit/BaseClasses/partialAHU.mo
AixLib/Airflow/AirHandlingUnit/NoAHU.mo
AixLib/Building/LowOrder/Examples/BuildingPhysicsExample.mo
AixLib/Building/LowOrder/Multizone/MultizoneEquipped.mo
README.md

small bugfixes related to hackday
merges master into development as preparation of release

Hackday bugfixes

---

AixLib/Airflow/AirHandlingUnit/AHU.mo

This should solve issue #242 
I can't run unittest, so i can't tell something about that, but in my test case this solution works.

#242, revised the equation of P_el to avoid divion by zero errors

---

AixLib/Utilities/Communication/SocketCommunication/Components/BaseClasses/PartialTCPCommunicator.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/SocketDisconnect.mo
AixLib/Utilities/Communication/SocketCommunication/UsersGuide/Contact.mo

This closes #281. There were still a few html errors, these have been fixed here. The table in `AixLib.Utilities.Communication.SocketCommunication.UsersGuide.Contact` does look a little less nice now, but uses correct html now.

Fix html for #281

---

AixLib/Fluid/MixingVolumes/Examples/HydraulicSeparator.mo
AixLib/Fluid/MixingVolumes/HydraulicSeparator.mo

Closes #287.
Results change mostly due to use of Annex 60 water medium in example.

Issue287 separator

---

AixLib/Utilities/HeatTransfer/HeatConv_outside.mo

...see commit.
This should close issue #306

Improved the model

---

AixLib/Utilities/Sources/ncDataReader.mo

See https://github.com/RWTH-EBC/AixLib/issues/313#issuecomment-278107763
@mlauster: Could you please merge these tiny changes.

issue_313: empty string is necessary in NcDataReader

---

AixLib/Resources/Include/AixLibSocketCommunication.h

Fix minor type issues

---

.github/CONTRIBUTING.md

#356
Adds Contributing.md file

Adds CONTRIBUTING.md file, let's see if it works in .github directory

---

AixLib/Utilities/Sources/NcDataReader.mo
AixLib/Utilities/Sources/ncDataReader.mo

This fixes #379. Please merge before the v0.5.0 release, as this is needed for AixLib to work in OpenModelica.

Issue379 syntax

---

AixLib/Fluid/HeatPumps/HeatPumpSimple.mo

Issue #373 states that in HeatPumpSimple there are missing documentations.
In this branch all the missing documentation is added.
Sorry Marcus, I don't know who else to assign.

Issue373_HPsimpledocumentation

---

AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo

Issue 394 is fixed.
Compilation of Multizone Example in JModelica is possible now.

Issue394 multizone n ports

---

AixLib/Airflow/AirHandlingUnit/AHU.mo
AixLib/Airflow/AirHandlingUnit/BaseClasses/PartialAHU.mo

Issue428_AHU_Vflow_eta

---

AixLib/FastHVAC/Components/HeatGenerators/HeatPump/HeatPump.mo

This Pull Request refers to the issue #452_FastHVAC
I just added "redeclare function" to the model.
In my opinion it doesn't change the model or did I miss some significant changes due to this addition?

modification of HeatPump model

---

AixLib/Building/HighOrder/House/OFD_MiddleInnerLoadWall/BuildingEnvelope/WholeHouseBuildingEnvelope.mo

... and delete 
`import AixLib;` statement.

use total path instead of relativ for two instances

---

AixLib/Electric/package.mo
AixLib/package.order

Added package.electric this solves #488

Issue488 package electric

---

AixLib/Electrical/package.mo
AixLib/package.order

Renaming Package Electric to Electrical

---

AixLib/DataBase/HeatPump/HeatPumpBaseDataDefinition.mo
AixLib/Fluid/HeatPumps/HeatPumpDetailed.mo
AixLib/Fluid/HeatPumps/HeatPumpSimple.mo

Correction of the documentation of HeatPumpDataBaseDefinition

#508 Correction of the documentation of HeatPumpDataBaseDefinition

---

AixLib/Controls/HVACAgentBasedControl/Agents/Broker.mo
AixLib/Controls/HVACAgentBasedControl/Agents/ColdProducerAgent.mo
AixLib/Controls/HVACAgentBasedControl/Agents/ConsumerAgent.mo
AixLib/Controls/HVACAgentBasedControl/Agents/HeatProducerAgent.mo
AixLib/Controls/HVACAgentBasedControl/Agents/IntermediateAgent.mo
AixLib/Controls/HVACAgentBasedControl/Agents/RoomAgent.mo
AixLib/Controls/HVACAgentBasedControl/BaseClasses/PartialAgent.mo
AixLib/Controls/HVACAgentBasedControl/BaseClasses/PartialCostFunction.mo
AixLib/Controls/HVACAgentBasedControl/BaseClasses/UDPSend_adapted.mo
AixLib/Controls/HVACAgentBasedControl/Examples/BuildingHeatingSystems/BuildingWithPV.mo
AixLib/Controls/HVACAgentBasedControl/Examples/HVACAgentsCommunications/SimpleCommunication.mo

Issue530 agents doc

---

AixLib/Utilities/HeatTransfer/HeatToStar.mo

Introduce max(T,100) to prevent negative solutions for the temperature
Related to #535.

issue535 prevent negative solutions for radiative temperature

---

AixLib/Fluid/HeatPumps/HeatPumpDetailed.mo

PT1_cycle parameter was not passed through.

---

AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo

fix html error

---

AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo

fix html mistake

---

AixLib/FastHVAC/Components/Storage/BaseClasses/PartialHeatTransferLayers.mo

Issue543 bugfix: record medium instead of package

---

AixLib/Fluid/Storage/BufferStorage.mo

See #545 
Works with OpenModelica now.

final parameter instead constant. use each and final.

---

AixLib/Building/Components/WindowsDoors/WindowSimple.mo

Issue571 window fix u value

---

AixLib/Airflow/AirHandlingUnit/Examples/AHU.mo
AixLib/Airflow/AirHandlingUnit/Examples/package.mo
AixLib/Airflow/AirHandlingUnit/Examples/package.order
AixLib/Resources/Scripts/Dymola/Airflow/AirHandlingUnit/Examples/AHU.mos

Issue578 ahu sim and plot

---

AixLib/FastHVAC/Components/Storage/HeatStorageVariablePorts.mo

Issue309 storages

---

AixLib/Utilities/Communication/SocketCommunication/Components/BaseClasses/PartialTCPCommunicator.mo
AixLib/Utilities/Communication/SocketCommunication/Components/TCPCommunicatorExample.mo
AixLib/Utilities/Communication/SocketCommunication/Examples/ExampleClientLoop.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/Internal/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/Utilities/package.mo
AixLib/Utilities/Communication/SocketCommunication/Functions/package.mo

Utilize TCP/IP socket communication from Modelica_DeviceDrivers.
TODO: 
* Possibly remove AixLibSocketCommunication.h
* Cleanup obsolete functions
Close #277

Fix socket communication

---

AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpControlledBase.mo
AixLib/Fluid/Storage/Examples/StorageSolarCollector.mo

Adds partial to GeothermalHeatPumpControlledBase to fix error and fixes example StorageSolarCollector
#603

Adds partial to GeothermalHeatPumpControlledBase to fix error

---

README.md

issue632 correct file and create more dependencies

---

AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
AixLib/ThermalZones/HighOrder/Components/Walls/Wall_ASHRAE140.mo

issue635 sunblind parameter enhancement

---

AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/SubstationCooling.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/SubstationHeating.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/SubstationHeatingCoolingFixDeltaT.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/SubstationHeatingCoolingVarDeltaT.mo

#403 This added SI-units for parameters and revisions for closed loop demand models

Issue403 dhc substations

---

AixLib/FastHVAC/Components/Pipes/BaseClasses/PipeBase.mo
AixLib/FastHVAC/Components/Storage/BaseClasses/HeatingCoil.mo
AixLib/package.mo

This should solve #640 and increase version number for a release

Issue460 versionnumber

---

README.md

Just a little integration for travis CI check into readme.md.

Integrated travis check image into readme.md

---

AixLib/Fluid/HeatPumps/HeatPumpSimple.mo
AixLib/package.mo

- Set gain value for evaporator to -1 to fix bug
- Increase version number

Fix bug in HeatPumpSimple

---

AixLib/Resources/Scripts/Dymola/Utilities/Examples/NcDataReader_win32.mos
AixLib/Resources/Scripts/Dymola/Utilities/Examples/NcDataReader_win64.mos
AixLib/Utilities/Examples/NcDataReader.mo
AixLib/Utilities/Sources/NcDataReader.mo

Issue658 nc data reader binaries

---

PUBLICATIONS.md
README.md

This should work as a first example how to add more publications. The link in the README.md will not work until the master merge. So you need to have a look at the PUBLICATIONS.md file by hand.
@LauraMaier @DaJansenGit @mlauster Could you please have a look and approve if you like it?
Workflow for new additions:
- Reopen the issue
- Recreate the branch
- Update you publications
- PR

Issue687 pubs

---

.gitignore

This closes #703 
@PMehrfeld @AnaConstantin could one of you review this? Thank you 😃

#703 updated gitignore in style of modelica-ibpsa

---

AixLib/package.mo
PUBLICATIONS.md

Issue754 pr update versions

---

AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BaseClasses/UPipeElement.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/EnergyPileGroup.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/EnergyPileSingle.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/Example/EnergyPileGroupExample.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/Example/package.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/Example/package.order
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/UPipe.mo
AixLib/FastHVAC/Components/HeatExchangers/Geothermal/BoreHoleHeatExchanger/package.order
AixLib/FastHVAC/Components/Pipes/BaseClasses/PipeBase.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipe.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipeAggregated.mo
AixLib/FastHVAC/Components/Pipes/package.mo
AixLib/FastHVAC/Examples/HeatExchangers/BoreHoleHeatExchanger/EnergyPileGroupExample.mo
AixLib/FastHVAC/Examples/HeatExchangers/BoreHoleHeatExchanger/VDI_Verification_EnergyPileGroupExample.mo
AixLib/FastHVAC/Examples/HeatExchangers/BoreHoleHeatExchanger/package.mo
AixLib/FastHVAC/Examples/HeatExchangers/BoreHoleHeatExchanger/package.order
AixLib/FastHVAC/Examples/HeatExchangers/package.order

Parallel pipes parameter

---

AixLib/FastHVAC/Components/Pipes/BaseClasses/PipeBase.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipe.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipeAggregated.mo

closes https://github.com/RWTH-EBC/AixLib/issues/771

Issue771 parallel pipe parameter

---

AixLib/FastHVAC/Components/HeatExchangers/BaseClasses/ML_thermal_delta.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipe.mo
AixLib/FastHVAC/Components/Pipes/DynamicPipeAggregated.mo
AixLib/Fluid/FixedResistances/Pipe.mo
AixLib/Fluid/HeatExchangers/ActiveWalls/BaseClasses/PanelHeatingSegment.mo
AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/MultiLayerThermalDelta.mo
AixLib/ThermalZones/HighOrder/Components/Walls/BaseClasses/ConvNLayerClearanceStar.mo
AixLib/ThermalZones/HighOrder/Components/WindowsDoors/Door.mo
AixLib/ThermalZones/HighOrder/Components/WindowsDoors/Window_ASHRAE140.mo
AixLib/Utilities/HeatTransfer/HeatToStar.mo
AixLib/Utilities/HeatTransfer/HeatToStar_Avar.mo
AixLib/Utilities/HeatTransfer/package.order
AixLib/Utilities/Sources/InternalGains/Humans/HumanSensibleHeatAreaSpecific.mo
AixLib/Utilities/Sources/InternalGains/Humans/HumanSensibleHeat_VDI2078.mo
AixLib/Utilities/Sources/InternalGains/Lights/LightsAreaSpecific.mo
AixLib/Utilities/Sources/InternalGains/Lights/Lights_Avar.mo
AixLib/Utilities/Sources/InternalGains/Lights/Lights_simple.mo
AixLib/Utilities/Sources/InternalGains/Machines/MachinesAreaSpecific.mo
AixLib/Utilities/Sources/InternalGains/Machines/Machines_Avar.mo
AixLib/Utilities/Sources/InternalGains/Machines/Machines_DIN18599.mo
AixLib/Utilities/Sources/InternalGains/Machines/Machines_simple.mo

This solves the issue discussed in #689 with the two different models by integrating all checked tasks. Have a look [here](https://github.com/RWTH-EBC/AixLib/issues/689#issuecomment-549816868)

Issue689 heat to star

---

AixLib/FastHVAC/HeatExchangers/BaseClasses/PseudoRadiator.mo
AixLib/FastHVAC/HeatExchangers/DHWHeatExchanger.mo
AixLib/FastHVAC/HeatExchangers/Examples/DHWHeatExchanger/DHWHeatExchanger.mo
AixLib/FastHVAC/HeatExchangers/Examples/MultiRadiator/ValidationMultiRadiator.mo
AixLib/FastHVAC/HeatExchangers/MultiRadiator.mo
AixLib/FastHVAC/Sensors/MassFlowSensor.mo
AixLib/FastHVAC/Valves/ThreeWayValve.mo

This PR reworks the multi radiator model and the DHW heat exchanger model of the FastHVAC to work with massflow as flow variable and improves the comprehensibility of the multi radiator  model. See also [this comment](https://github.com/RWTH-EBC/AixLib/issues/790#issuecomment-546289068_).

issue309 - rework heat exchangers

---

.gitmodules
AixLib/Utilities/Sources/NcDataReader.mo
README.md

Delete uses annotation for ncDataReader #826

---

PUBLICATIONS.md

add BAS puclication #831

---

AixLib/Systems/HydraulicModules/BaseClasses/PartialHydraulicModule.mo
AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpHeadControlled.mo
AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_SpeedControlledNrpm.mo
AixLib/Systems/HydraulicModules/BaseClasses/package.order
AixLib/Systems/HydraulicModules/Controller/CtrMix.mo
AixLib/Systems/HydraulicModules/Controller/CtrPump.mo
AixLib/Systems/HydraulicModules/Controller/CtrThrottle.mo
AixLib/Systems/HydraulicModules/SimpleConsumer.mo
AixLib/Systems/HydraulicModules/package.order

Issue862 minor fixes in hydraulic modules

---

AixLib/Fluid/FixedResistances/Pipe.mo

#867 multiplication with nParallel in heatConv in Pipe.mo added

---

AixLib/Utilities/Assertions/RealPassThroughWithAssertion.mo
AixLib/Utilities/Assertions/package.mo
AixLib/Utilities/Assertions/package.order
AixLib/Utilities/package.order

This closes #884 
@LauraMaier: Feel free to merge after approval (if you approve ;) )

Add assertion real pass through model

---

AixLib/DataBase/HeatPump/HeatPumpBaseDataDefinition.mo

Delete implicit <p> and not opened </p>

---

README.md

Issue971 Readme git clone command

---

README.md

this closes #973 
we should merge this also into master.

Issue973 adjust cloning description

---

AixLib/FastHVAC/Components/HeatExchangers/BaseClasses/ML_thermal_delta.mo
AixLib/Fluid/FixedResistances/Pipe.mo
AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/MultiLayerThermalDelta.mo
AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/RadiatorWall.mo
AixLib/Media/AirIncompressible.mo
AixLib/Media/Specialized/Water/ConstantProperties_pT/package.mo
AixLib/Types/Tilt/package.mo

This closes #983 
This closes #981

Issue983: Correct some HTML errors manually

---

AixLib/ThermalZones/ReducedOrder/Examples/MultizonePartlyCooled.mo
AixLib/ThermalZones/ReducedOrder/Examples/package.order
AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo

should solve the issue shown in #986 
closes #986

Issue986 cooler on differnt setting

---

AixLib/Systems/HydraulicModules/SimpleConsumer.mo

#799 plugFlowPipe removed in simple consumer

---

AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/DHCSubstationHeatPumpDirectCooling.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/package.order
AixLib/Fluid/DistrictHeatingCooling/Demands/Examples/DHCSubstationHeatPumpDirectCooling.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/Examples/package.order
AixLib/Fluid/DistrictHeatingCooling/Supplies/ClosedLoop/DHCSupplyHeaterCoolerStorage.mo
AixLib/Fluid/DistrictHeatingCooling/Supplies/ClosedLoop/package.order
AixLib/Fluid/DistrictHeatingCooling/Supplies/Examples/DHCSupplyHeaterCoolerStorage.mo
AixLib/Fluid/DistrictHeatingCooling/Supplies/Examples/package.order

This PR is part of #403 and has as its goal to standardize the naming of models, submodels, parameters and vaiables in the dhc package.

Issue403 dhc closed loop

---

AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/DHCSubstationHeatPumpChiller.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/ClosedLoop/package.order
AixLib/Fluid/DistrictHeatingCooling/Demands/Examples/DHCSubstationHeatPumpChiller.mo
AixLib/Fluid/DistrictHeatingCooling/Demands/Examples/package.order

#403 This adds the second closed loop substation model for 5th generation dhc with heat pump and chiller.

#403 next try to add second closed loop substation to dhc package

---

AixLib/Resources/Scripts/ConvertAixLib_from_0.10.5_to_0.10.6.mos

For #1044
Fixes Bug in conversion-script. Thanks @LauraMaier for your hint. :)

Fixes conversion-script for conversion from 0.10.5 to 0.10.6

---

AixLib/Controls/VentilationController/VentilationController.mo

This closes https://github.com/RWTH-EBC/AixLib/issues/560

slight changes in the info box

---

AixLib/BoundaryConditions/InternalGains/Humans/BaseClasses/TemperatureDependentMoistureOutputSIA2024.mo

Propagate it until deepest model

---

AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo

https://github.com/RWTH-EBC/AixLib/issues/1053

propagate zoneParam.specificPeople to co2-model

---

.gitlab-ci.yml

Fix bug in gitlab-ci.yml

---

AixLib/Fluid/FixedResistances/GenericPipe.mo

@alexanderAKU: 1 min review only!
This closes #1047

Fix withConvection bug in GenericPipe

---

AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeEmbedded.mo
AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
AixLib/Fluid/DistrictHeatingCooling/Pipes/StaticPipe.mo

Renaming of parameters and variables in DHC pipe models according to new DHCPipe

#403 renaming of parameters and variables according to DHCPipe

---

AixLib/Controls/HeatPump/SafetyControls/BaseClasses/BoundaryMap.mo
AixLib/Controls/HeatPump/SafetyControls/BaseClasses/BoundaryMapIcon.mo
AixLib/Controls/HeatPump/SafetyControls/OperationalEnvelope.mo
AixLib/Controls/HeatPump/SafetyControls/SafetyControl.mo
AixLib/Systems/HeatPumpSystems/BaseClasses/HPSystemController.mo
AixLib/Systems/HeatPumpSystems/BaseClasses/PartialHeatPumpSystem.mo
AixLib/package.mo

Issue1160: Heat pump control -> Hysteresis of operational envelope

---

AixLib/Controls/HeatPump/SafetyControls/BaseClasses/BoundaryMap.mo

Closes #1204
I just used the correct `tableUpp_internal` and not `tableUpp`.

Fix bug of wrong table usage

---

AixLib/Systems/HydraulicModules/Controller/CalcHydraulicPower.mo
AixLib/Systems/HydraulicModules/Controller/CtrThrottleQFlow.mo
AixLib/Systems/HydraulicModules/Controller/package.order

Issue1207 add power based subsystem controllers

---

AixLib/Systems/HydraulicModules/Controller/CalcHydraulicPower.mo

#1213 fixed wrong parameter name

---

bin/templates/03_ci_templates/02_UnitTests/simulate_model.gitlab-ci.yml
bin/templates/03_ci_templates/02_UnitTests/simulate_model.txt

-  delete Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 && in the before script section
-   python dymola interface start with command xvfb-run -n 77 python bin/CITests/02_UnitTests/CheckPackages/validatetest.py

Fix gitlab templates

---

AixLib/package.mo

Update update Modelica_DeviceDrivers to version 2.0.0 in uses to fix issue: #1323.

Fix #1323, update Modelica_DeviceDrivers to 2.0.0 in uses

---

AixLib/Utilities/Sensors/ExergyMeter/FlowExergyMeter.mo
AixLib/Utilities/Sensors/ExergyMeter/StoredExergyMeter.mo

issue1340_OpenModelica compatibility for ExergyMeter

---

AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/EnthalpyExchanger.mo

Closes #1351 
This PR solves the openModelica failure of membrane-based enthalpy exchanger model.

Issue1351 membrane based enthalpy exchnager om

---

AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo

#1372 heatingRod OpenModelica

---

AixLib/Fluid/Movers/Examples/package.order
AixLib/Obsolete/Year2021/Fluid/Examples/PumpHydraulicResistance_closedLoop.mo
AixLib/Obsolete/Year2021/Fluid/Examples/package.order

Moved example of obsolete model in obsolete package accordning to #1363

Moved example of obsolete model also in obsolete package

---

AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
AixLib/Systems/ModularAHU/Examples/Cooler.mo
AixLib/Systems/ModularAHU/Examples/Heater.mo
AixLib/Systems/ModularAHU/Validation/AHU2_Cooler.mo
AixLib/Systems/ModularAHU/Validation/AHU2_Heater.mo
AixLib/Systems/ModularAHU/Validation/AHU2_Preheater.mo

Closes #1345 .
This PR will handle the problems of modular ahu model with OpenModelica.

Issue1345 modular ahu open modelica

---

AixLib/DataBase/Pumps/PumpPolynomialBased/Examples/testMaxMinHeightTable.mo
AixLib/DataBase/Pumps/PumpPolynomialBased/Examples/testPumpHeadCalculation.mo
AixLib/DataBase/Pumps/PumpPolynomialBased/Examples/testPumpPowerCalculation.mo
AixLib/DataBase/Pumps/PumpPolynomialBased/Examples/testPumpSpeedCalculation.mo

fix comparison #1411

---

AixLib/Fluid/Solar/Thermal/SolarThermal.mo

Fix division error #1452

---

AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/package.order

remove duplicate RadiatorTypes
